//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IService1")]
public interface IService1
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetBike", ReplyAction = "http://tempuri.org/IService1/GetBikeResponse")]
    int GetBike(string apiKey, string numberToFind, string j);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetBike", ReplyAction = "http://tempuri.org/IService1/GetBikeResponse")]
    System.Threading.Tasks.Task<int> GetBikeAsync(string apiKey, string numberToFind, string j);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetStation", ReplyAction = "http://tempuri.org/IService1/GetStationResponse")]
    string GetStation(string apiKey, string city);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetStation", ReplyAction = "http://tempuri.org/IService1/GetStationResponse")]
    System.Threading.Tasks.Task<string> GetStationAsync(string apiKey, string city);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetCity", ReplyAction = "http://tempuri.org/IService1/GetCityResponse")]
    string GetCity(string apiKey);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetCity", ReplyAction = "http://tempuri.org/IService1/GetCityResponse")]
    System.Threading.Tasks.Task<string> GetCityAsync(string apiKey);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IService1Channel : IService1, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class Service1Client : System.ServiceModel.ClientBase<IService1>, IService1
{

    public Service1Client()
    {
    }

    public Service1Client(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public Service1Client(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public int GetBike(string apiKey, string numberToFind, string j)
    {
        return base.Channel.GetBike(apiKey, numberToFind, j);
    }

    public System.Threading.Tasks.Task<int> GetBikeAsync(string apiKey, string numberToFind, string j)
    {
        return base.Channel.GetBikeAsync(apiKey, numberToFind, j);
    }

    public string GetStation(string apiKey, string city)
    {
        return base.Channel.GetStation(apiKey, city);
    }

    public System.Threading.Tasks.Task<string> GetStationAsync(string apiKey, string city)
    {
        return base.Channel.GetStationAsync(apiKey, city);
    }

    public string GetCity(string apiKey)
    {
        return base.Channel.GetCity(apiKey);
    }

    public System.Threading.Tasks.Task<string> GetCityAsync(string apiKey)
    {
        return base.Channel.GetCityAsync(apiKey);
    }
}
